import type { AchievementKey, GAchievement } from "./achievements";
import type { AnimationKey, GAnimation } from "./animations";
import type { ClassKey, GClass } from "./classes";
import type { ConditionKey, GCondition } from "./conditions";
import type { CraftKey, GCraft } from "./craft";
import type { DimensionKey, GDimension } from "./dimensions";
import type { DismantleKey, GDismantle } from "./dismantle";
import type { DocKey, GDoc } from "./docs";
import type { DropKey, GDrop } from "./drops";
import type { EmotionKey, GEmotion } from "./emotions";
import type { EventKey, GEvent } from "./events";
import type { GameKey, GGame } from "./games";
import type { GeometryKey, GGeometry } from "./geometry";
import type { ImageKey, GImage } from "./images";
import type { ImagesetKey, GImageset } from "./imagesets";
import type { ItemKey, GItem } from "./items";
import type { LevelKey, GLevel } from "./levels";
import type { MapKey, GMap } from "./maps";
import type { MonsterKey, GMonster } from "./monsters";
import type { MultiplierKey, GMultiplier } from "./multipliers";
import type { NpcKey, GNpc } from "./npcs";
import type { PositionKey, GPosition } from "./positions";
import type { ProjectileKey, GProjectile } from "./projectiles";
import type { SetKey, GSet } from "./sets";
import type { SkillKey, GSkill } from "./skills";
import type { SpriteKey, GSprite } from "./sprites";
import type { TilesetKey, GTileset } from "./tilesets";
import type { TitleKey, GTitle } from "./titles";
import type { TokenKey, GToken } from "./tokens";

export type GData = {
  achievements: { [T in AchievementKey]: GAchievement };
  animations: { [T in AnimationKey]: GAnimation };
  classes: { [T in ClassKey]: GClass };
  conditions: { [T in ConditionKey]: GCondition };
  craft: { [T in CraftKey]: GCraft };
  dimensions: { [T in DimensionKey]: GDimension };
  dismantle: { [T in DismantleKey]: GDismantle };
  docs: { [T in DocKey]: GDoc };
  drops: { [T in DropKey]: GDrop };
  emotions: { [T in EmotionKey]: GEmotion };
  events: { [T in EventKey]: GEvent };
  games: { [T in GameKey]: GGame };
  geometry: { [T in GeometryKey]: GGeometry };
  images: { [T in ImageKey]: GImage };
  imagesets: { [T in ImagesetKey]: GImageset };
  items: { [T in ItemKey]: GItem };
  levels: { [T in LevelKey]: GLevel };
  maps: { [T in MapKey]: GMap };
  monsters: { [T in MonsterKey]: GMonster };
  multipliers: { [T in MultiplierKey]: GMultiplier };
  npcs: { [T in NpcKey]: GNpc };
  positions: { [T in PositionKey]: GPosition };
  projectiles: { [T in ProjectileKey]: GProjectile };
  sets: { [T in SetKey]: GSet };
  skills: { [T in SkillKey]: GSkill };
  sprites: { [T in SpriteKey]: GSprite };
  tilesets: { [T in TilesetKey]: GTileset };
  titles: { [T in TitleKey]: GTitle };
  tokens: { [T in TokenKey]: GToken };
};
