import type { ItemKey } from "../items/index";
import type { JarKey } from "../items/Jar";
import type { NpcKey } from "../npcs/Npcs";
import type { SkillKey } from "../skills/Skills";

export type CraftKey =
  | "anchorbelt"
  | "armorring"
  | "basketofeggs"
  | "bataxe"
  | "beastmantle"
  | "bfangamulet"
  | "bogcrown"
  | "bogwalkers"
  | "bowofthedead"
  | "brinefang"
  | "bronzeingot"
  | "cake"
  | "candleward"
  | "candycanesword"
  | "carrotsword"
  | "cave_ambercoat"
  | "cave_counterweight"
  | "cave_deepaxe"
  | "cave_loaded_die"
  | "cave_locktooth"
  | "cave_mothsteps"
  | "cave_reedscythe"
  | "cave_tunnelaxe"
  | "cclaw"
  | "charmer"
  | "cinderboots"
  | "cinderwand"
  | "cloverstud"
  | "cocoon"
  | "computer"
  | "covemantle"
  | "ctristone"
  | "daggerofthedead"
  | "dartgun"
  | "djinncrown"
  | "elixirdex1"
  | "elixirdex2"
  | "elixirfires"
  | "elixirfzres"
  | "elixirint1"
  | "elixirint2"
  | "elixirpnres"
  | "elixirstr1"
  | "elixirstr2"
  | "elixirvit1"
  | "elixirvit2"
  | "emberhood"
  | "emberseal"
  | "fclaw"
  | "fierygloves"
  | "fireblade"
  | "firebow"
  | "firestaff"
  | "firestars"
  | "frostbow"
  | "froststaff"
  | "fsword"
  | "glacierseal"
  | "gloampendant"
  | "goldingot"
  | "gstaff"
  | "guestbook"
  | "harpybow"
  | "hbow"
  | "heartwood"
  | "homecomingcape"
  | "homecomingcoat"
  | "homecominghelm"
  | "keepsakependant"
  | "knifebelt"
  | "lanternshield"
  | "lbelt"
  | "maceofthedead"
  | "makeawishjar"
  | "merry"
  | "molehook"
  | "moonshardearring"
  | "mossheart"
  | "mushroomstaff"
  | "oathplate"
  | "offeringx"
  | "orba"
  | "orbg"
  | "ornamentstaff"
  | "paradequiver"
  | "pickaxe"
  | "platinumingot"
  | "pmaceofthedead"
  | "pollenbow"
  | "pouchbow"
  | "quiver"
  | "ratkingbuckler"
  | "ratworkcoat"
  | "reedpants"
  | "reefvest"
  | "resistancering"
  | "resolutesallet"
  | "reunionbow"
  | "rimeboots"
  | "rimeknuckles"
  | "rod"
  | "saffronloop"
  | "scribeorb"
  | "silkgrips"
  | "sixcake"
  | "slimestaff"
  | "snakeoil"
  | "snowflakes"
  | "spearofthedead"
  | "staffofthedead"
  | "starcloak"
  | "stealthcape"
  | "stillwaterlens"
  | "stinger"
  | "stormquiver"
  | "supercomputer"
  | "swordofthedead"
  | "thistlequiver"
  | "threadneedle"
  | "thundergrips"
  | "turtleshard"
  | "venomband"
  | "vowkeepergloves"
  | "wattire"
  | "wblade"
  | "wbreeches"
  | "wcap"
  | "weaver"
  | "wgloves"
  | "windbelt"
  | "wingedboots"
  | "worldrootcrook"
  | "wshoes"
  | "xbox";

export interface GCraft {
  cost: number;
  items: Array<
    [quantity: number, item: ItemKey] | [quantity: number, item: ItemKey, level: number]
  >;
  output?: {
    data: SkillKey;
    name: JarKey;
  };
  quest?: NpcKey;
}

export type GCrafts = Record<CraftKey, GCraft> &
  Partial<Record<Exclude<ItemKey, CraftKey>, undefined>>;

