import type { ItemKey } from "../items/index";
import type { NpcKey } from "../npcs/Npcs";

export type CraftKey =
  | "armorring"
  | "basketofeggs"
  | "bfangamulet"
  | "bowofthedead"
  | "bronzeingot"
  | "cake"
  | "candycanesword"
  | "carrotsword"
  | "cclaw"
  | "charmer"
  | "computer"
  | "ctristone"
  | "daggerofthedead"
  | "dartgun"
  | "elixirdex1"
  | "elixirdex2"
  | "elixirfires"
  | "elixirfzres"
  | "elixirint1"
  | "elixirint2"
  | "elixirpnres"
  | "elixirstr1"
  | "elixirstr2"
  | "elixirvit1"
  | "elixirvit2"
  | "fclaw"
  | "fierygloves"
  | "fireblade"
  | "firebow"
  | "firestaff"
  | "firestars"
  | "frostbow"
  | "froststaff"
  | "fsword"
  | "goldingot"
  | "gstaff"
  | "harpybow"
  | "hbow"
  | "heartwood"
  | "lbelt"
  | "maceofthedead"
  | "merry"
  | "mushroomstaff"
  | "offeringx"
  | "orbg"
  | "ornamentstaff"
  | "pickaxe"
  | "platinumingot"
  | "pmaceofthedead"
  | "pouchbow"
  | "quiver"
  | "resistancering"
  | "rod"
  | "slimestaff"
  | "snakeoil"
  | "snowflakes"
  | "spearofthedead"
  | "staffofthedead"
  | "stealthcape"
  | "stinger"
  | "supercomputer"
  | "swordofthedead"
  | "wattire"
  | "wblade"
  | "wbreeches"
  | "wcap"
  | "wgloves"
  | "wingedboots"
  | "wshoes"
  | "xbox";

export interface GCraft {
  items: Array<
    [quantity: number, item: ItemKey] | [quantity: number, item: ItemKey, level: number]
  >;
  cost: number;
  quest?: NpcKey;
}

export type GCrafts = Record<CraftKey, GCraft> &
  Partial<Record<Exclude<ItemKey, CraftKey>, undefined>>;
